// Code generated by volcago. DO NOT EDIT.
// generated version: v1.0.0
package repository

const (
	UserIndexLabelNameEqual       = "n4" // perfect-match of Name
	UserIndexLabelNameLike        = "n3" // like-match of Name
	UserIndexLabelNamePrefix      = "n1" // prefix-match of Name
	UserIndexLabelNameSuffix      = "n2" // suffix-match of Name
	UserIndexLabelAgePrefix       = "a1" // prefix-match of Age
	UserIndexLabelAgeSuffix       = "a2" // suffix-match of Age
	UserIndexLabelAgeLike         = "a3" // like-match of Age
	UserIndexLabelAgeEqual        = "a4" // perfect-match of Age
	UserIndexLabelCreatedAtPrefix = "c1" // prefix-match of CreatedAt
	UserIndexLabelCreatedAtSuffix = "c2" // suffix-match of CreatedAt
	UserIndexLabelCreatedAtLike   = "c3" // like-match of CreatedAt
	UserIndexLabelCreatedAtEqual  = "c4" // perfect-match of CreatedAt
	UserIndexLabelCreatedByEqual  = "c8" // perfect-match of CreatedBy
	UserIndexLabelCreatedByLike   = "c7" // like-match of CreatedBy
	UserIndexLabelCreatedByPrefix = "c5" // prefix-match of CreatedBy
	UserIndexLabelCreatedBySuffix = "c6" // suffix-match of CreatedBy
	UserIndexLabelUpdatedAtPrefix = "u1" // prefix-match of UpdatedAt
	UserIndexLabelUpdatedAtSuffix = "u2" // suffix-match of UpdatedAt
	UserIndexLabelUpdatedAtLike   = "u3" // like-match of UpdatedAt
	UserIndexLabelUpdatedAtEqual  = "u4" // perfect-match of UpdatedAt
	UserIndexLabelUpdatedByEqual  = "u8" // perfect-match of UpdatedBy
	UserIndexLabelUpdatedByLike   = "u7" // like-match of UpdatedBy
	UserIndexLabelUpdatedByPrefix = "u5" // prefix-match of UpdatedBy
	UserIndexLabelUpdatedBySuffix = "u6" // suffix-match of UpdatedBy
	UserIndexLabelDeletedAtPrefix = "d1" // prefix-match of DeletedAt
	UserIndexLabelDeletedAtSuffix = "d2" // suffix-match of DeletedAt
	UserIndexLabelDeletedAtLike   = "d3" // like-match of DeletedAt
	UserIndexLabelDeletedAtEqual  = "d4" // perfect-match of DeletedAt
	UserIndexLabelDeletedByEqual  = "d8" // perfect-match of DeletedBy
	UserIndexLabelDeletedByLike   = "d7" // like-match of DeletedBy
	UserIndexLabelDeletedByPrefix = "d5" // prefix-match of DeletedBy
	UserIndexLabelDeletedBySuffix = "d6" // suffix-match of DeletedBy
	UserIndexLabelVersionPrefix   = "v1" // prefix-match of Version
	UserIndexLabelVersionSuffix   = "v2" // suffix-match of Version
	UserIndexLabelVersionLike     = "v3" // like-match of Version
	UserIndexLabelVersionEqual    = "v4" // perfect-match of Version
)
